[project]
name = "contractor"
version = "0.1.0"
description = "Use llm to generate openapi specification from code"
authors = [
    {name = "grauwolf32"}
]
readme = "README.md"
requires-python = ">=3.10,<4.0"
dependencies = [
    "google-adk (>=1.21.0,<2.0.0)",
    "litellm (>=1.80.12,<2.0.0)"
]

[dependency-groups]
dev = [
    "ruff (>=0.14.10,<0.15.0)",
    "pytest (>=9.0.2,<10.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = ["."]
